### ISSUE TITLE
[/goods] のビューでXSSが可能

### ISSUE THREAD

**Issue by SShayashi** [teeGraco/ponkotsu_store#1]
以下、やること
- [ ] ビュー側でエスケープ

**Comment by teeGraco** [comment]
### 再現
レビューに
```
<button type="button" onclick="alert('ぽんこつストアへようこそ！')">CLICK</button>
```
と入力するとボタンが表示 => クリックでJS発火。
vueのv-htmlが明らかに悪さをしている(されている)ので、その辺の修正が必要。

**Comment by teeGraco** [comment]
**他人のブラウザで任意のJavaScriptを実行**

に該当するか
